## Homework 01-intro

In [58]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [4]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(url)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [8]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [19]:
df.fuel_type.nunique()

3

In [18]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [34]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [39]:
median = df.horsepower.median()
median

np.float64(254.0)

In [41]:
mode = df.horsepower.mode()
mode

0    252.0
Name: horsepower, dtype: float64

In [42]:
df.horsepower.fillna(mode).median()

np.float64(254.0)

#### Q7

In [54]:
asia = df[df['origin']=='Asia']
asia.head(2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8

In [52]:
asia_sel = asia[['vehicle_weight', 'model_year']]
asia_sel.head(2)

   vehicle_weight  model_year
2            4240        1996
6            4310        1992

In [50]:
X = asia_sel.head(7).to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [55]:
XTX = X.T@X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [59]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [60]:
w = np.linalg.inv(XTX) @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [61]:
sum(w)

np.float64(0.36919696904925486)